id: P004477
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W23426
  title: བོན་པོའི་ཡིག་ཆ་ལས་མངོན་པའི་སྐོར།
  author: ''
  volumes:
    f441d54b829b4c75b2ded240b7e6e80c:
      image_group_id: I1588
      title: ''
      volume_number: 1
      total_pages: 582
      base_file: v001.txt
