id: I06D540F3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T20:42:29+00:00'
last_modified: '2022-06-08T01:21:55.282371+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23426
  title: བོན་པོའི་ཡིག་ཆ་ལས་མངོན་པའི་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    54DA:
      image_group_id: I1588
      title: ''
      total_pages: 582
      order: 1
      base_file: 54DA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
