id: I06D540F3
legacy_id: P004477
ocr_import_info:
  bdrc_scan_id: W23426
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T20:39:10'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:03:22.224075+00:00'
last_modified: 2022-09-02 09:03:37.291228
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23426
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23426
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བོན་པོའི་ཡིག་ཆ་ལས་མངོན་པའི་སྐོར།
  author: སློབ་དཔོན་བསྟན་འཛིན་རྣམ་དག
statistics:
  ocr_word_mean_confidence_index: 0.6934068251910788
  ocr_word_median_confidence_index: 0.7699999809265137
quality: null
bases:
  I1588:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1588
      total_pages: 582
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1588.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.6934068251910788
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
